### ISSUE TITLE
10.0.17134.885

### ISSUE THREAD

**Issue by Benjamin-Loison** [fre4kyC0de/rdpwrap#15]
No patch for 10.0.17134.885, could you send one please or post a kind of video to explain how to do the right stuff to write by ourselves the stuff to add in the config file please ?

**Comment by s0nic9** [comment]
no problems here with current patch 706 because last july windows update version 10.0.17134.885 doesn't update the dll

**Comment by Benjamin-Loison** [comment]
Thanks but when I add the following: https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.17134.706.txt
after the rdpwrap.ini content in C:\Program Files\RDP Wrapper, and after a RDPWInst.exe -r, RDPConf.exe shows a green "fully supported" but Service state goes green Running for a few seconds after having done RDPWInst.exe -r, but after it goes in red to Stopped

@s0nic9 help please ?

**Comment by s0nic9** [comment]
remember to add a blank line at the end of the ini then restart

**Comment by Benjamin-Loison** [comment]
Wow it works, thank you very much... Where have you learnt this information ?

**Comment by s0nic9** [comment]
"je me suis cassé les dents cette semaine !"
I read many topics if not all then many try & see way !

**Comment by patricknelson** [comment]
**Summary:** (for other n00bs like me)

1. Config for `10.0.17134.706` ([link here](https://raw.githubusercontent.com/fre4kyC0de/rdpwrap/master/10.0.17134.706.txt)) does actually work for Windows `10.0.17134.885` (RDP version is unchanged) and can tell from the service version reported in `RDPConf.exe`.
2. Add an **extra line** at bottom of `rdpwrap.ini`, otherwise the service will fail when attempting to restart it (see `services.msc`).

I was missing step 2, my mistake as well (new user here). Thanks for the help @s0nic9!

**Comment by fre4kyC0de** [comment]
I added a notice about the required blank line at the end
https://github.com/fre4kyC0de/rdpwrap/commit/55e0200fbdf6cc69f64d5a2a12ec90ca9658a0e6
