### ISSUE TITLE
Possible Update [10.0.18362.657]

### ISSUE THREAD

**Issue by ngenen** [fre4kyC0de/rdpwrap#34]
Hello there! I've been testing and the patch code for 10.0.18362.267, worked pretty well for 10.0.18362.657, the one you have published untested makes the TermService crash.

The hide users and one session per user works great, so I can guess everything works just right..

```
[10.0.18362.657]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FB5
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DBFC
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.657-SLInit]
bInitialized.x64 =F6A8C
bServerSku.x64 =F6A90
lMaxUserSessions.x64 =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64 =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64 =F6AAC
```

**Comment by fre4kyC0de** [comment]
Actually the offsets you posted and the ones I published do not differ. Maybe some kind of copy-paste mistake? Missing empty line at the end? Inserted with LF line ending instead of CRLF?

Here is a diff of the offsets you posted and the x64-part of the ones I published:
![diff](https://user-images.githubusercontent.com/9489794/80929818-81305900-8d9e-11ea-9351-24094aaf851b.png)

**Comment by fre4kyC0de** [comment]
No answer...
